<template>
  <q-form @submit.prevent="submitForm">
    <!-- User Name input -->
    <q-input
      v-model="formData.username"
      label="Rose Miller"
      outlined
      dense
      :rules="[charsRule, twoWordsRule]"
      @keyup.enter="handleEnterKey"
    />
    <!-- Version 2
     Email input
    <q-input
      v-model="formData.email"
      label="Email"
      outlined
      dense
      :rules="[emailRule]"
      @keyup.enter="handleEnterKey"
    />
    -->
    <!-- Add more input fields as needed -->

    <q-btn v-if="isFormValid" type="submit" label="Submit" color="primary" />
  </q-form>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { User } from '../models/User';

export default defineComponent({
  name: 'UserForm',
  props: {
    method: {
      type: String,
      required: true,
      validator: (value: string) => {
        return ['add', 'update'].includes(value);
      },
    },
    user: {
      type: Object as () => User | null,
      default: null,
    },
    onAddUser: {
      type: Function,
      default: null,
    },
    onUpdateUser: {
      type: Function,
      default: null,
    },
  },
  setup(props) {
    const isFormValid = ref(false);
    const isFormInit = ref(false);
    const formData = {
      username: '',
      /* email: '', // version 2 */
    };
    if (props.method === 'update' && props.onUpdateUser && props.user) {
      formData.username = props.user.name;
      /* formData.email = props.user.email; // version 2 */
    }
    /* const emailRule = () => {
      if (isFormInit.value) return true;
      const isValid = /^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/.test(formData.email);
      return isValid || 'Invalid email format';
    } // version 2 */
    const charsRule = () => {
      if (isFormInit.value) return true;
      const isValid = /^[a-zA-Z0-9-' ']+$/.test(formData.username);
      return isValid || 'Only alphanumeric characters are allowed';
    };
    const twoWordsRule = () => {
      if (isFormInit.value) return true;
      const words = formData.username.trim().split(' ');
      const isValid = words.length >= 2 && words.every((word) => word !== '');
      return isValid || 'Must have at least 2 words';
    };
    const handleEnterKey = (event: { preventDefault: () => void }) => {
      if (isFormInit.value) {
        isFormInit.value = false;
        event.preventDefault();
      }
      // Check all rules and update isFormValid
      isFormValid.value = charsRule() === true && twoWordsRule() === true;
      /*&& emailRule() === true // version 2 */

      if (!isFormValid.value) {
        // Prevent form submission on Enter key if the form is not valid
        event.preventDefault();
      }
    };
    const submitForm = () => {
      if (isFormValid.value) {
        if (props.method === 'add' && props.onAddUser) {
          const newUser = {
            id: Date.now(), // do not care about the id value (generated by sqlite)
            name: formData.username,
            active: 1,
            /* email: formData.email, // version 2 */
          };
          if (typeof props.onAddUser === 'function') {
            props.onAddUser(newUser);
          }
        } else if (
          props.method === 'update' &&
          props.onUpdateUser &&
          props.user
        ) {
          const updateUser = {
            id: props.user.id,
            name: formData.username,
            active: props.user.active,
            /* email: formData.email, // version 2 */
          };
          if (typeof props.onUpdateUser === 'function') {
            props.onUpdateUser(updateUser);
          }
        }
        console.log('Form submitted with data:', formData);
        console.log('re-init formData.username');
        formData.username = '';
        /* formData.email = ''; // version 2 */
        isFormInit.value = true;
        isFormValid.value = false;
      }
    };
    return {
      formData,
      charsRule,
      twoWordsRule,
      submitForm,
      isFormValid,
      handleEnterKey,
      /* emailRule, // Version 2 */
    };
  },
});
</script>
